# Generated by Django 4.2.4 on 2023-08-09 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='userses',
            new_name='user',
        ),
    ]
