# Generated by Django 4.2.4 on 2023-08-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_rename_users_author_rename_userses_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
